import { Routes } from '@angular/router';
import { LandingComponent } from './landing/landing.component';
import { LoginComponent } from './auth/login/login.component';
import { DashboardComponent } from './pages/admin/dashboard/dashboard.component';
import { EmployeeDashboardComponent } from './pages/employee/employee-dashboard/employee-dashboard.component';
import { DepartmentManagementComponent } from './pages/admin/system-administration/department-management/department-management.component';
import { UserManagementComponent } from './pages/admin/system-administration/user-management/user-management.component';
import { OrgManagementComponent } from './pages/admin/system-administration/org-management/org-management.component';
import { EmployeeManagementComponent } from './pages/admin/employee-management/employee-management.component';
import { FinalPayProcessComponent } from './pages/admin/payroll-management/final-pay-process/final-pay-process.component';
import { PayslipCenterComponent } from './pages/admin/payroll-management/payslip-center/payslip-center.component';
import { RunPayrollComponent } from './pages/admin/payroll-management/run-payroll/run-payroll.component';
import { ThirteenMonthPayComponent } from './pages/admin/payroll-management/thirteen-month-pay/thirteen-month-pay.component';
import { PayrollManagementComponent } from './pages/admin/payroll-management/payroll-management.component';
import { ContirbutionsDeductionsComponent } from './pages/admin/contirbutions-deductions/contirbutions-deductions.component';
import { MandatoryContributionsComponent } from './pages/admin/contirbutions-deductions/mandatory-contributions/mandatory-contributions.component';
import { DeductionsComponent } from './pages/admin/contirbutions-deductions/deductions/deductions.component';
import { LoansComponent } from './pages/admin/contirbutions-deductions/loans/loans.component';
import { LeaveRequestsComponent } from './pages/admin/leave-management/leave-requests/leave-requests.component';
import { LeaveSettingsComponent } from './pages/admin/leave-management/leave-settings/leave-settings.component';
import { LeaveReportsComponent } from './pages/admin/leave-management/leave-reports/leave-reports.component';
import { ReportsRemittancesComponent } from './pages/admin/reports-remittances/reports-remittances.component';
import { PayrollSummaryComponent } from './pages/admin/reports-remittances/payroll-summary/payroll-summary.component';
import { LlcSummaryComponent } from './pages/admin/reports-remittances/llc-summary/llc-summary.component';
import { GovtReportsComponent } from './pages/admin/reports-remittances/govt-reports/govt-reports.component';
import { BankFileGenerationComponent } from './pages/admin/bank-file-generation/bank-file-generation.component';


export const routes: Routes = [
  { path: '', component: LandingComponent },
  { path: 'landing', component: LandingComponent },
  { path: 'login', component: LoginComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'employee-dashboard', component: EmployeeDashboardComponent },
  { path: 'department-management', component: DepartmentManagementComponent },
  { path: 'user-management', component: UserManagementComponent },
  { path: 'org-management', component: OrgManagementComponent },
  { path: 'employee-management', component: EmployeeManagementComponent },
  { path: 'final-pay-process', component: FinalPayProcessComponent },
  { path: 'payslip-center', component: PayslipCenterComponent },
  { path: 'run-payroll', component: RunPayrollComponent },
  { path: 'thirteen-month-pay', component: ThirteenMonthPayComponent },
  { path: 'payroll-management', component: PayrollManagementComponent },
  { path: 'contributions-deductions', component: ContirbutionsDeductionsComponent },
  { path: 'mandatory-contributions', component: MandatoryContributionsComponent }, 
  { path: 'deductions', component: DeductionsComponent },
  { path: 'loans', component: LoansComponent },
  { path: 'leave-requests', component: LeaveRequestsComponent },
  { path: 'leave-settings', component: LeaveSettingsComponent },
  { path: 'leave-reports', component: LeaveReportsComponent },
  { path: 'reports-remittances', component: ReportsRemittancesComponent },
  { path: 'payroll-summary', component: PayrollSummaryComponent },
  { path: 'llc-summary', component: LlcSummaryComponent },
  { path: 'govt-reports', component: GovtReportsComponent },
  { path: 'bank-file-generation', component: BankFileGenerationComponent },
  { path: '**', redirectTo: '' },
];
